name: Test
on:
    - push

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        container: arangodb
        steps:
            - uses: actions/checkout@master
              with:
                fetch-depth: 1
            - name: Install Foxx microservice
              run: foxx install /inventory
            - name: Test status endpoint
              run: wget --quiet --tries=1 --spider http://localhost:8529/_db/_system/inventory/status
